/**
 * @param { import(knex).Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex('providers').del()
    await knex('providers').insert([
        {
            id: 1,
            service_id: 1,
            provider_name: 'John Doe',
            provider_address: '123 Main Street',
            city: 'Burnaby',
            country: 'Canada',
            contact_phone: '+1 (123) 456-7890',
            contact_email: 'john@gmail.com',
            rating: 4.5,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'Plumbing Repair': '$100 per hour',
                'Fixture Installation': '$150 per fixture',
                'Drain Cleaning': '$80 per hour',
                'Water Heater Repair': '$200 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.24377441,
            longitude: -122.98169708
        },
        {
            id: 2,
            service_id: 2,
            provider_name: 'Jane Smith',
            provider_address: '456 Oak Avenue',
            city: 'New Westminster',
            country: 'Canada',
            contact_phone: '+1 (234) 567-8901',
            contact_email: 'jane@gmail.com',
            rating: 4.2,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'Electrical Repair': '$90 per hour',
                'Wiring Installation': '$120 per fixture',
                'Light Fixture Installation': '$80 per hour',
                'Circuit Breaker Replacement': '$150 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.21960831,
            longitude: -122.90846252
        },
        {
            id: 3,
            service_id: 6,
            provider_name: 'Michael Johnson',
            provider_address: '789 Maple Drive',
            city: 'Burnaby',
            country: 'Canada',
            contact_phone: '+1 (345) 678-9012',
            contact_email: 'michael@gmail.com',
            rating: 4.8,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'HVAC Repair': '$120 per hour',
                'Air Duct Cleaning': '$120 flat fee',
                'Thermostat Replacement': '$100 per hour',
                'HVAC System Installation': '$1500 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.24377441,
            longitude: -122.98169708
        },
        {
            id: 4,
            service_id: 1,
            provider_name: 'Emily Brown',
            provider_address: '101 Elm Street',
            city: 'New Westminster',
            country: 'Canada',
            contact_phone: '+1 (456) 789-0123',
            contact_email: 'emily@gmail.com',
            rating: 4.6,
            availability: "yes",
            provider_image: '/images/providers/face-women-1.jpg',
            pricing: {
                'Plumbing Repair': '$100 per hour',
                'Fixture Installation': '$150 per fixture',
                'Drain Cleaning': '$80 per hour',
                'Water Heater Repair': '$200 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.21960831,
            longitude: -122.90846252
        },
        {
            id: 5,
            service_id: 4,
            provider_name: 'William Davis',
            provider_address: '202 Cedar Avenue',
            city: 'Burnaby',
            country: 'Canada',
            contact_phone: '+1 (567) 890-1234',
            contact_email: 'william@gmail.com',
            rating: 4.3,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'Garden Design': '$100 per hour',
                'Tree Trimming': '$80 per hour',
                'Lawn Maintenance': '$50 per hour',
                'Irrigation System Installation': '$150 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.24377441,
            longitude: -122.98169708
        },
        {
            id: 6,
            service_id: 3,
            provider_name: 'Emma Wilson',
            provider_address: '303 Pine Drive',
            city: 'Delta',
            country: 'Canada',
            contact_phone: '+1 (678) 901-2345',
            contact_email: 'emma@gmail.com',
            rating: 4.9,
            availability: "yes",
            provider_image: '/images/providers/face-women-1.jpg',
            pricing: {
                'Deep Cleaning': '$50 per hour',
                'House Cleaning': '$30 per hour',
                'Carpet Cleaning': '$100 per hour',
                'Office Cleaning': '$40 flat fee'
            },
            experience: '7 Years',
            isFavorite: 0,
            latitude: 49.0846258,
            longitude: -123.057938
        },
        {
            id: 7,
            service_id: 1,
            provider_name: 'James Taylor',
            provider_address: '404 Oak Street',
            city: 'Delta',
            country: 'Canada',
            contact_phone: '+1 (789) 012-3456',
            contact_email: 'james@gmail.com',
            rating: 4.4,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'Plumbing Repair': '$100 per hour',
                'Fixture Installation': '$150 per fixture',
                'Drain Cleaning': '$80 per hour',
                'Water Heater Repair': '$200 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.0846258,
            longitude: -123.057938
        },
        {
            id: 8,
            service_id: 2,
            provider_name: 'Olivia Martinez',
            provider_address: '505 Pine Avenue',
            city: 'Delta',
            country: 'Canada',
            contact_phone: '+1 (890) 123-4567',
            contact_email: 'olivia@gmail.com',
            rating: 4.1,
            availability: "yes",
            provider_image: '/images/providers/face-women-2.jpg',
            pricing: {
                'Electrical Repair': '$90 per hour',
                'Wiring Installation': '$120 per fixture',
                'Light Fixture Installation': '$80 per hour',
                'Circuit Breaker Replacement': '$150 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.0846258,
            longitude: -123.057938
        },
        {
            id: 9,
            service_id: 3,
            provider_name: 'Benjamin Jones',
            provider_address: '606 Elm Drive',
            city: 'Surrey',
            country: 'Canada',
            contact_phone: '+1 (901) 234-5678',
            contact_email: 'benjamin@gmail.com',
            rating: 4.7,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'Deep Cleaning': '$50 per hour',
                'House Cleaning': '$30 per hour',
                'Carpet Cleaning': '$100 per hour',
                'Office Cleaning': '$40 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.10460281,
            longitude: -122.82350922
        },
        {
            id: 10,
            service_id: 1,
            provider_name: 'Sophia Garcia',
            provider_address: '707 Cedar Street',
            city: 'Surrey',
            country: 'Canada',
            contact_phone: '+1 (012) 345-6789',
            contact_email: 'sophia@gmail.com',
            rating: 4.5,
            availability: "yes",
            provider_image: '/images/providers/face-women-2.jpg',
            pricing: {
                'Plumbing Repair': '$100 per hour',
                'Fixture Installation': '$150 per fixture',
                'Drain Cleaning': '$80 per hour',
                'Water Heater Repair': '$200 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.10460281,
            longitude: -122.82350922
        },
        {
            id: 11,
            service_id: 2,
            provider_name: 'Liam Rodriguez',
            provider_address: '808 Maple Avenue',
            city: 'Surrey',
            country: 'Canada',
            contact_phone: '+1 (123) 456-7890',
            contact_email: 'liam@gmail.com',
            rating: 4.2,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'Electrical Repair': '$90 per hour',
                'Wiring Installation': '$120 per fixture',
                'Light Fixture Installation': '$80 per hour',
                'Circuit Breaker Replacement': '$150 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.10460281,
            longitude: -122.82350922
        },
        {
            id: 12,
            service_id: 3,
            provider_name: 'Isabella Wilson',
            provider_address: '909 Oak Drive',
            city: 'Vancouver',
            country: 'Canada',
            contact_phone: '+1 (234) 567-8901',
            contact_email: 'isabella@gmail.com',
            rating: 4.8,
            availability: "yes",
            provider_image: '/images/providers/face-women-2.jpg',
            pricing: {
                'Deep Cleaning': '$50 per hour',
                'House Cleaning': '$30 per hour',
                'Carpet Cleaning': '$100 per hour',
                'Office Cleaning': '$40 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.26356506,
            longitude: -123.13857269
        },
        {
            id: 13,
            service_id: 6,
            provider_name: 'Mason Brown',
            provider_address: '111 Pine Street',
            city: 'Vancouver',
            country: 'Canada',
            contact_phone: '+1 (345) 678-9012',
            contact_email: 'mason@gmail.com',
            rating: 4.6,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'HVAC Repair': '$120 per hour',
                'Air Duct Cleaning': '$120 flat fee',
                'Thermostat Replacement': '$100 per hour',
                'HVAC System Installation': '$1500 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.26356506,
            longitude: -123.13857269
        },
        {
            id: 14,
            service_id: 5,
            provider_name: 'Ava Davis',
            provider_address: '222 Elm Avenue',
            city: 'Delta',
            country: 'Canada',
            contact_phone: '+1 (456) 789-0123',
            contact_email: 'ava@gmail.com',
            rating: 4.3,
            availability: "yes",
            provider_image: '/images/providers/face-women-2.jpg',
            pricing: {
                'Garden Design': '$100 per hour',
                'Tree Trimming': '$80 per hour',
                'Lawn Maintenance': '$50 per hour',
                'Irrigation System Installation': '$150 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.0846258,
            longitude: -123.057938
        },
        {
            id: 15,
            service_id: 4,
            provider_name: 'Lucas Miller',
            provider_address: '333 Cedar Drive',
            city: 'Burnaby',
            country: 'Canada',
            contact_phone: '+1 (567) 890-1234',
            contact_email: 'lucas@gmail.com',
            rating: 4.9,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'Garden Design': '$100 per hour',
                'Tree Trimming': '$80 per hour',
                'Lawn Maintenance': '$50 per hour',
                'Irrigation System Installation': '$150 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.24377441,
            longitude: -122.98169708
        },
        {
            id: 16,
            service_id: 7,
            provider_name: 'Alex Anderson',
            provider_address: '123 Cedar Avenue',
            city: 'Burnaby',
            country: 'Canada',
            contact_phone: '+1 (604) 111-2222',
            contact_email: 'alex@gmail.com',
            rating: 4.8,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'Roof Installation': '$2000 per square',
                'Roof Repair': '$150 per hour',
                'Roof Inspection': '$250 flat fee'
            },
            experience: '10 Years',
            isFavorite: 1,
            latitude: 49.2827,
            longitude: -123.1207
        },
        {
            id: 17,
            service_id: 7,
            provider_name: 'Roofing Solutions',
            provider_address: '456 Oakwood Street',
            city: 'Vancouver',
            country: 'Canada',
            contact_phone: '+1 (604) 333-4444',
            contact_email: 'roofsolutions@example.com',
            rating: 4.9,
            availability: "yes",
            provider_image: '/images/providers/face-women-2.jpg',
            pricing: {
                'Roof Installation': '$2000 per square',
                'Roof Repair': '$150 per hour',
                'Roof Inspection': '$250 flat fee'
            },
            experience: '8 Years',
            isFavorite: 0,
            latitude: 49.2827,
            longitude: -123.1207
        },
        {
            id: 18,
            service_id: 7,
            provider_name: 'Coquitlam Roofing Experts',
            provider_address: '789 Maplewood Avenue',
            city: 'Coquitlam',
            country: 'Canada',
            contact_phone: '+1 (604) 555-6666',
            contact_email: 'coqroof@example.com',
            rating: 4.7,
            availability: "yes",
            provider_image: '/images/providers/face-women-1.jpg',
            pricing: {
                'Roof Installation': '$2000 per square',
                'Roof Repair': '$150 per hour',
                'Roof Inspection': '$250 flat fee'
            },
            experience: '6 Years',
            isFavorite: 1,
            latitude: 49.2827,
            longitude: -123.1207
        },
        {
            id: 19,
            service_id: 8,
            provider_name: 'Burnaby Carpentry Masters',
            provider_address: '321 Elm Street',
            city: 'Burnaby',
            country: 'Canada',
            contact_phone: '+1 (604) 777-8888',
            contact_email: 'burnabycarpentry@example.com',
            rating: 4.6,
            availability: "yes",
            provider_image: '/images/providers/face-women-1.jpg',
            pricing: {
                'Custom Furniture': '$130 per hour',
                'Cabinet Installation': '$190 per fixture',
                'Woodworking': '$100 per hour'
              },
            experience: '12 Years',
            isFavorite: 0,
            latitude: 49.2827,
            longitude: -123.1207
        },
        {
            id: 20,
            service_id: 8,
            provider_name: 'Vancouver Carpentry Solutions',
            provider_address: '654 Pine Avenue',
            city: 'Vancouver',
            country: 'Canada',
            contact_phone: '+1 (604) 999-1010',
            contact_email: 'vcarpentry@example.com',
            rating: 4.9,
            availability: "yes",
            provider_image: '/images/providers/face-women-1.jpg',
            pricing: {
              'Custom Furniture': '$130 per hour',
              'Cabinet Installation': '$190 per fixture',
              'Woodworking': '$100 per hour'
            },
            experience: '9 Years',
            isFavorite : 1,
            latitude: 49.2827,
            longitude: -123.1207
          },
          {
            id: 21,
            service_id: 5,
            provider_name: 'Rema William',
            provider_address: '222 Elm Avenue',
            city: 'Surrey',
            country: 'Canada',
            contact_phone: '+1 (456) 789-0123',
            contact_email: 'rema@gmail.com',
            rating: 4.3,
            availability: "yes",
            provider_image: '/images/providers/face-women-2.jpg',
            pricing: {
                'Garden Design': '$100 per hour',
                'Tree Trimming': '$80 per hour',
                'Lawn Maintenance': '$50 per hour',
                'Irrigation System Installation': '$150 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude:  49.10460281,
            longitude: -122.82350922
        },
        {
            id: 22,
            service_id: 5,
            provider_name: 'Nobel Abraham',
            provider_address: '222 Elm Avenue',
            city: 'Coquitlam',
            country: 'Canada',
            contact_phone: '+1 (456) 789-0123',
            contact_email: 'nobel@gmail.com',
            rating: 4.3,
            availability: "yes",
            provider_image: '/images/providers/face-man-1.jpg',
            pricing: {
                'Garden Design': '$100 per hour',
                'Tree Trimming': '$80 per hour',
                'Lawn Maintenance': '$50 per hour',
                'Irrigation System Installation': '$150 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.28505325,
            longitude: -122.79459381
        },
        {
            id: 23,
            service_id: 5,
            provider_name: 'Lorem',
            provider_address: '222 Elm Avenue',
            city: 'Delta',
            country: 'Canada',
            contact_phone: '+1 (456) 789-0123',
            contact_email: 'lorem@gmail.com',
            rating: 4.3,
            availability: "yes",
            provider_image: '/images/providers/face-women-2.jpg',
            pricing: {
                'Garden Design': '$100 per hour',
                'Tree Trimming': '$80 per hour',
                'Lawn Maintenance': '$50 per hour',
                'Irrigation System Installation': '$150 flat fee'
            },
            experience: '5 Years',
            isFavorite: 0,
            latitude: 49.0846258,
            longitude: -123.057938
        },   
    ]
    );
};
